[[ilm]]
= Curator and Index Lifecycle Management

[partintro]
--

Beginning with Elasticsearch version 6.6, Elasticsearch has provided
{ref}/index-lifecycle-management.html[Index Lifecycle Management] (or, ILM) to
users with at least a Basic license. ILM provides users with many of the most
common index management features as a matter of policy, rather than execution
time analysis (which is how Curator works).

--

[[ilm-actions]]
== ILM Actions

ILM applies policy actions as indices enter time-oriented phases:

* Hot
* Warm
* Cold
* Delete

[[ilm-or-curator]]
== ILM or Curator?

If ILM provides the functionality to manage your index lifecycle, and you have
at least a Basic license, consider using ILM in place of Curator. Many of the
Stack components make use of ILM by default.

[[ilm-and-curator]]
== ILM and Curator!

WARNING: Curator will not act on any index associated with an ILM policy without
  setting `allow_ilm_indices` to `true`.

Curator and ILM _can_ coexist. However, to prevent Curator from accidentally
interfering, or colliding with ILM policies, any index associated with an ILM
policy name is excluded by default. This is true whether you have a Basic
license or not, or whether the ILM policy is enabled or not.

Curator can be configured to work with ILM-enabled indices by setting the
<<option_allow_ilm,`allow_ilm_indices`>> option to `true` for any action.

Learn more about Index Lifecycle Management
{ref}/index-lifecycle-management.html[here].
