[[elasticsearch-curator]]

== Elasticsearch Curator CLI

This document shows how to use the Elasticsearch CLI.  If you wish to learn
about the Elasticsearch Curator API, please visit
http://curator.readthedocs.org/

[float]
=== Click-based CLI

Curator now uses http://click.pocoo.org/3/[Click] for its command-line library.
This has made the code cleaner, and easier to read and extend.  The end result
should not look very different from previous versions.

[float]
==== Nested command structure

Commands may require their own arguments, which must come _before_
subsequent nested commands.

--------
$ curator --host 10.0.0.2 show indices --all-indices
--------

In this instancewe see that the base command has the `--host` parameter set. The
nested command `show` follows with no argument before the command `indices`,
which has the `--all-indices` parameter.

You can use `--help` after _any_ command.  If `--help` were inserted between
the `show` command and `indices`, it would display the help output for the
`show` command, and exit.

NOTE: `--help` is your friend.  Consult `--help` early and often.

[float]
=== Curator Command "tree"

----------------------------------
$ curator
    ├── alias
    │     └── indices
    ├── allocation
    │     └── indices
    ├── bloom
    │     └── indices
    ├── close
    │     └── indices
    ├── delete
    │     └── indices
    │     └── snapshots
    ├── open
    │     └── indices
    ├── optimize
    │     └── indices
    ├── replicas
    │     └── indices
    ├── show
    │     └── indices
    │     └── snapshots
    └── snapshot
          └── indices
----------------------------------

Each command and subcommand in the tree will have different options (or none!).

=== Commands and Arguments

The root command structure looks like this:

-----
Usage: curator [OPTIONS] COMMAND [ARGS]...

  Curator for Elasticsearch indices. See
  http://github.com/elasticsearch/curator/wiki

Options:
  --host TEXT        Elasticsearch host.
  --url_prefix TEXT  Elasticsearch http url prefix.
  --port INTEGER     Elasticsearch port.
  --use_ssl          Connect to Elasticsearch through SSL.
  --http_auth TEXT   Use Basic Authentication ex: user:pass
  --timeout INTEGER  Connection timeout in seconds.
  --master-only      Only operate on elected master node.
  --dry-run          Do not perform any changes.
  --debug            Debug mode
  --loglevel TEXT    Log level
  --logfile TEXT     log file
  --logformat TEXT   Log output format [default|logstash].
  --version          Show the version and exit.
  --help             Show this message and exit.

Commands:
  alias       Index Aliasing
  allocation  Index Allocation
  bloom       Disable bloom filter cache
  close       Close indices
  delete      Delete indices or snapshots
  open        Open indices
  optimize    Optimize Indices
  replicas    Replica Count Per-shard
  show        Show indices or snapshots
  snapshot    Take snapshots of indices (Backup)
-----

The `--help` output of the other commands can be seen here:

- <<alias>>
- <<allocation>>
- <<bloom>>
- <<close>>
- <<delete>>
- <<open>>
- <<optimize>>
- <<replicas>>
- <<show>>
- <<snapshot>>

Subcommands:

- <<indices>>
- <<snapshots>>


[float]
=== Using the <<indices>> and <<snapshots>> subcommands

Beginning with Curator v3, index filtering flags can be combined.  The flags
which allow this are:

- <<older-than>>
- <<newer-than>>
- <<prefix>>
- <<suffix>>
- <<regex>>
- <<exclude>>
- <<index>>
- <<snapshot-flag>>
- <<timestring>>

[float]
==== Examples

- Delete _all_ indices with matching <<timestring>> which are older than 30 days
+
-----
curator --host 10.0.0.2 delete indices --older-than 30 --time-unit days \
   --timestring '%Y.%m.%d'
-----
+
In previous versions of Curator, you would have needed as many runs of the
command-line as you had prefixes, no matter the matching pattern.  Not so any
more!  With this example, _all_ indices with a pattern of `%Y.%m.%d` inside will
be deleted.  This is useful for managing both Logstash and Marvel indices with
a single command, if you want the same retention period.

NOTE: Kibana indices are omitted from deletion by default.

- Alias a subset of indices
+
-----
curator --host 10.0.0.2 alias --name lastmonth indices --newer-than 60 \
   --older-than 30 --timestring '%Y.%m.%d' --time-unit days --prefix logstash
-----
+
In this example, logstash indices older than 30 days--but newer than 60--are
added to alias `lastmonth`.  Please note that Curator does not create aliases.
It can only add to them or remove from them.  Let's take this example further,
though.
+
-----
curator --host 10.0.0.2 alias --name lastmonth --remove indices --older-than 60 \
   --timestring '%Y.%m.%d' --time-unit days --prefix logstash
curator --host 10.0.0.2 alias --name lastmonth indices --newer-than 60 \
   --older-than 30 --timestring '%Y.%m.%d' --time-unit days --prefix logstash
-----
+
The updated, 2 line example now _removes_ indices older than 60 days first, and
then proceeds to make sure that everything between 30 and 60 days is in the
alias.  Note that Curator will not re-alias if the index is already in the
alias.

- Optimize only the specified indices
+
-----
curator --host 10.0.0.2 optimize --max_num_segments 1 --delay 120 \
   --index indexname1 --index indexname2
-----
+
This command will _only_ operate on the named indices, `indexname1` and
`indexname2`.  It will pause for `120` seconds after optimizing each index.

- Show only indices with a timestring
+
-----
curator --host 10.0.0.2 show indices --timestring '%Y.%m.%d'
-----
+
While timestring may nearly always be seen alongside <<older-than>>,
<<newer-than>>, and <<time-unit>>, there may be cases when you just want to act
on indices with a timestamp in the name.

- Close all indices, excepting those matching patterns `kibana` and
`logstash-2015.03`
+
-----
curator --host 10.0.0.2 close indices --exclude kibana --exclude logstash-2015.03
-----
+
In this case, all indices saving those matching pattern `kibana`, or all
Logstash indices for the month of March 2015 will be closed.




[float]
=== Flags

[float]
[[prefix]]
=== prefix

-----
--prefix TEXT                   Include only items beginning with
                                prefix.
-----

- Appears in <<indices>> and <<snapshots>> nested commands

[float]
[[suffix]]
=== suffix

-----
--suffix TEXT                   Include only items ending with suffix.
-----

- Appears in <<indices>> and <<snapshots>> nested commands

[float]
[[regex]]
=== regex

-----
--regex TEXT                    Provide your own regex, e.g
                                '^prefix-.*-suffix$'
-----

- Appears in <<indices>> and <<snapshots>> nested commands

These may be able to be quite complex.  Your imagination may be the limit.  Be
sure to test with <<show>> first, or use the `--dry_run` flag.

[float]
[[exclude]]
=== exclude

-----
--exclude TEXT                  Exclude matching items. Can be invoked
                                multiple times.
-----

- Appears in <<indices>> and <<snapshots>> nested commands

You can exclude multiple patterns by invoking `--exclude` multiple times.

[float]
[[index]]
=== index

-----
--index TEXT                    Include the provided index in the list. Can
                                be invoked multiple times.
-----

- Appears in <<indices>> nested command

You can include multiple indices by invoking `--index` multiple times.

[float]
[[snapshot-flag]]
=== snapshot (flag)

-----
--snapshot TEXT                 Include the provided snapshot in the list.
                                Can be invoked multiple times.
-----

- Appears in <<snapshots>> nested command

You can include multiple snapshots by invoking `--snapshot` multiple times.

[float]
[[older-than]]
=== older-than

-----
--older-than INTEGER            Include only items older than n
                                time_units
-----

- Appears in <<indices>> and <<snapshots>> nested commands

This flag is dependent on both <<time-unit>> and <<timestring>>

[float]
[[newer-than]]
=== newer-than

-----
--newer-than INTEGER            Include only items newer than n
                                time_units
-----

- Appears in <<indices>> and <<snapshots>> nested commands

This flag is dependent on both <<time-unit>> and <<timestring>>

[float]
[[timestring]]
=== timestring

-----
--timestring TEXT               Python strftime string to match your item
                                definition, e.g. 2014.07.15 would be
                                %Y.%m.%d
-----

- Appears in <<indices>> and <<snapshots>> nested commands

Learn more about
https://docs.python.org/2/library/datetime.html#strftime-and-strptime-behavior[strftime].

[float]
[[time-unit]]
=== time-unit

-----
--time-unit [hours|days|weeks|months]
                                Unit of time to reckon by
-----

- Appears in <<indices>> and <<snapshots>> nested commands

<<newer-than>> or <<older-than>> is used as a multiplier of `--time-unit`.  If
`--older-than` is 5 and `--time-unit` is days, the calculated time period will
be "5 days."

[float]
=== Help output
include::alias.asciidoc[]
include::allocation.asciidoc[]
include::bloom.asciidoc[]
include::close.asciidoc[]
include::delete.asciidoc[]
include::open.asciidoc[]
include::optimize.asciidoc[]
include::replicas.asciidoc[]
include::show.asciidoc[]
include::snapshot.asciidoc[]
include::indices.asciidoc[]
include::snapshots.asciidoc[]
