# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "elastic/centos-6-x86_64"

  config.vm.provision "shell", inline: <<-SHELL
    sudo yum -y groupinstall "Development Tools"
    sudo yum -y install python-devel zlib-devel bzip2-devel sqlite sqlite-devel openssl-devel
  SHELL

  config.vm.synced_folder "/curator_packages", "/curator_packages", create: true, owner: "vagrant", group: "vagrant"
  config.vm.synced_folder "/curator_source", "/curator_source", create: true, owner: "vagrant", group: "vagrant"

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--nictype1", "virtio"]
  end
end
