[glossary]
= Glossary of terms


TIP: If you'd like to see a term defined here, use the "Edit" link to the
right. See <<site-corrections,Site Corrections>>.

[glossary]
alias::
    A pointer to one or more indices.  See
    {ref}/indices-aliases.html[Index Aliases] in the official Elasticsearch
    documentation for more information.

bloom::
    This refers to a Bloom filter cache.  A
    http://en.wikipedia.org/wiki/Bloom_filter[Bloom filter] can be used to speed
    up answers in a key-value storage system.  Beginning with version 1.4,
    Elasticsearch no longer uses a Bloom filter cache for search operations.

command::
    An operation to perform on one or more indices or snapshots. See
    <<commands>>.

subcommand::
    A command which is nested, or comes after, a prior command.  See
    <<subcommand>>.

time-unit::
    One of `hours`, `days`, `weeks`, or `months`.  When acting on time-series
    indices, the <<time-unit>> is used for time calculation.

timestring::
    A http://strftime.org[Python strftime] string to match your index
    definition. 2014.07.15 would be `%Y.%m.%d`.  See <<timestring>>.
