# syntax=docker/dockerfile:experimental@sha256:600e5c62eedff338b3f7a0850beb7c05866e0ef27b2d2e8c02aa468e78496ff5
ARG VERSION=ES_VERSION
FROM elasticsearch:${VERSION}

COPY --chown=1000:0 small.options /usr/share/elasticsearch/config/jvm.options.d
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
CMD ["eswrapper"]
