[[bloom]]
== bloom

IMPORTANT: Beginning with version 1.4, Elasticsearch no longer enables bloom
filters for search. This command is unnecessary if your Elasticsearch version is
1.4 or higher.

[float]
Summary
~~~~~~~

From the
http://www.elastic.co/guide/en/elasticsearch/reference/0.90/index-modules-codec.html#bloom-postings[Elasticsearch
Bloom Filter Posting Format documentation]

_______________________________________________________________________________
It can sometime make sense to disable bloom filters. For instance, if you are
logging into an index per day, and you have thousands of indices, the bloom
filters can take up a sizable amount of memory. For most queries you are only
interested in recent indices, so you don’t mind CRUD operations on older indices
taking slightly longer.

In these cases you can disable loading of the bloom filter on a per-index basis
by updating the index settings
_______________________________________________________________________________

&nbsp;

This setting is especially relevant to Logstash and Marvel use-cases. The
`bloom` command allows you to disable the bloom filter cache for indices.

[float]
Flags
~~~~~

-----------------------------------------------------------------------------
$ curator bloom --help
Usage: curator bloom [OPTIONS] COMMAND [ARGS]...

  Disable bloom filter cache

Options:
  --delay INTEGER  Pause *n* seconds after disabling bloom filter cache of an
                   index  [default: 0]
  --help           Show this message and exit.

Commands:
  indices  Index selection.
-----------------------------------------------------------------------------

&nbsp;

IMPORTANT: This command requires the <<indices-subcommand,indices>>
<<subcommand,subcommand>> for <<index-selection,index selection>>.

[float]
Example
~~~~~~~

Disable the bloom filters (for Elasticsearch versions < 1.4):

----------------------------------------------------
curator bloom indices <<index selection parameters>>
----------------------------------------------------
