[[close]]
== close

[float]
Summary
~~~~~~~

From the
{ref}/indices-open-close.html[Elasticsearch Open/Close API documentation]

________________________________________________________________________________
The open and close index APIs allow to close an index, and later on re-open it.
A closed index has almost no overhead on the cluster (except for maintaining its
metadata & the disk space it consumes), and is blocked for read/write
operations. A closed index can be opened which will then go through the normal
recovery process.
________________________________________________________________________________

Sometimes it makes sense to close an index so as to reduce cluster overhead, but
meet data retention requirements. The `close` command makes it possible to do in
a scripted way.

NOTE: Starting with Curator 3.2.0, if you have Elasticsearch 1.6.0 or later, the
_close_ command will attempt to perform a <<seal,synced flush>>, or _seal_ each
index before closing, which should lead to faster recovery times.

[float]
Flags
~~~~~

------------------------------------------------
$ curator close --help
Usage: curator close [OPTIONS] COMMAND [ARGS]...

  Close indices

Options:
  --help  Show this message and exit.

Commands:
  indices  Index selection.
------------------------------------------------

&nbsp;

IMPORTANT: This command requires the <<indices-subcommand,indices>>
<<subcommand,subcommand>> for <<index-selection,index selection>>.

[float]
Example
~~~~~~~

Close matching indices:

----------------------------------------------------
curator close indices <<index selection parameters>>
----------------------------------------------------
