[[skip-repo-validation]]
== --skip-repo-validation

[float]
Summary
~~~~~~~

New feature added in Curator 3.2.0

IMPORTANT: This flag only functions within the scope of the <<snapshot>> command.

Skip {ref}/modules-snapshots.html#_repository_verification[repository access validation].
This is useful in cases where your shared filesystem (local or remote) is
functional but slow enough to respond that Elasticsearch yields a false-positive
test result.  This condition is also usually intermittent, rather than constant.

WARNING: Repository validation is performed in order to ensure your snapshots
will all be able to write to the repository.  It is not recommended to skip this
check unless you have verified that all is working, as expected.

[float]
Flags
~~~~~

* `--skip-repo-validation` Skip repository access validation.

[float]
Examples
~~~~~~~~

Snapshot indices matching the selection parameters to the named repository,
skipping repository validation:

----------------------------------------------------------------------------------------------------------
curator snapshot --skip-repo-validation --repository REPOSITORY_NAME indices <<index selection paramters>>
----------------------------------------------------------------------------------------------------------
